#!/usr/bin/bash

git clone --recursive https://github.com/rodrigozhou/.vim.git ~/.vim
git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
ln -s ~/.vim/vimrc ~/.vimrc
cd ~/.vim
vim +PluginInstall
